# Generated by Django 5.0.2 on 2025-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='drawing_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='shared_text',
            field=models.TextField(blank=True),
        ),
    ]
