# Generated by Django 5.0.2 on 2025-04-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_drawing_data_room_shared_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drawing',
        ),
    ]
