# Generated by Django 5.0.2 on 2025-04-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_host_remove_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
